version: '3'
services:
  authentication-service:
    image: authentication-service
    build: .
    ports:
      - '3000:3000'
    environment: 
      PORT: 3000
      AUTH_CALLBACK_URL: http://localhost:3000/auth/callback
      SESSION_SECRET: very-secret
      SHRAGA_URL: http://13.79.7.3
      SECRET_KEY: iamsososecret!youcaneverguess
      TOKEN_KEY: token
      DB_NAME: task
      CLIENT_ENDPOINT: http://localhost:80/
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    
